Sylius training proposal
lchrusciel/pehapkari.cz pull request #1
Opened 2018-04-03 14:50 UTC by lchrusciel

2018-04-03 15:14 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +Have you heard about Sylius E-Commerce framework? If so, you know already that it is an important part of Symfony ecosystem and it is one of the biggest, publicly available projects developed in BDD
you know already -> you already know

2018-04-03 15:26 UTC, dukusz requested changes

2018-04-03 15:26 UTC, dukusz commented on source/_data/users.yml
> +            bio: "With Sylius from the early beginning, currently in the role of Software Engineer and Training Terminator. Kind of an API-guy, pragmatic developer in love with tests automatization a
Training Terminator -> Trainer

2018-04-03 15:26 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +perex: "Comprehensive introduction to Sylius E-Commerce framework. Join us and learn how to customize one of the most promising e-commerce solution."
E-Commerce -> eCommerce or e-commerce

2018-04-03 15:26 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +Have you heard about Sylius E-Commerce framework? If so, you know already that it is an important part of Symfony ecosystem and it is one of the biggest, publicly available projects developed in BDD
E-commerce -> e-commerce
you know already -> you already know
join me and check that -> join me and learn the e-commerce technology of the future. Forget legacy platforms like Magento or PrestaShop. Just enjoy being a developer again!

2018-04-03 15:26 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +After training you should be familiar with Sylius eco system and you should be able to decide if Sylius suites your needs.
with Sylius ecosystem -> with Sylius basics and will be able to start your first e-commerce project.

2018-04-03 15:26 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +Training will be done in english.
english -> English

2018-04-03 15:26 UTC, dukusz commented on source/_lectures/getting-started-with-sylius.md
> +
Maybe add some BDD basics?

2018-04-04 06:47 UTC, lchrusciel commented on source/_lectures/getting-started-with-sylius.md
> +
not enough time :(

2018-04-04 07:46 UTC, closed without merging